# Site settings
title: Médecin Généraliste Denis Fleurette
description: "DR DENIS FLEURETTE cabinet médical"
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the name of your domain
logo_url: svg/min/logo.svg

# Hero
hero: 
    hero_img: hero.jpg
    hero_title: Docteur Denis Fleurette
    hero_description: DR DENIS FLEURETTE cabinet médical

# Contact form
api_token: # Enter API token here

# Contact info
contact:
    phone: 04 66 59 25 39
    emergency: 15
    email: contact-dr@fleurette.me
    address: 4 Quai du Général de Gaulle, Résidence Le Riva, 30300 Beaucaire

# Opening hours
monday_friday: 9:00 – 18:00
saturday: 10:00 – 17:00
sunday: 10:00 – 15:00

# Testimonials
testimonials:
    testimonials_img: parallax.jpg

# Map
map:
    zoom: 17
    address: 4 Quai du Général de Gaulle, Résidence Le Riva, 30300 Beaucaire
    address_details: svg/min/logo.svg

# Social settings
facebook:
twitter:
instagram: 
youtube: 
skype: 
feed: no

# Footer
copyright: © 2017 Docteur Denis Fleurette - Tous droits réservés

# Build settings
markdown: kramdown

exclude: [
    package.json,
    Gruntfile.js,
    node_modules,
    .sass-cache,
    Gemfile,
    Gemfile.lock,
    .gitignore
]

# Theme Settings
analytics: 
google_verification:
